import type { ConfigProduto } from "./tipos";

export const esquadria: ConfigProduto = {
  id: "esquadria",
  nome: "Esquadrias Encomenda",
  tituloDocumento: "ENCOMENDA ESPECIAL ESQUADRIAS",
  prazoEntregaDias: 60,
  campoLargura: "largura",
  campoAltura: "altura",
  campos: [
    {
      id: "categoria",
      tipo: "multipla-escolha",
      label: "Categoria",
      opcoes: ["PANORÂMICO", "SEMI-PANORÂMICO", "QUADRICULADO", "VENEZIANA"],
      gruposExcludentes: [["PANORÂMICO", "SEMI-PANORÂMICO", "QUADRICULADO"]],
      exibirApenasSelecionadas: true,
    },
    { id: "altura", tipo: "medida", unidade: "m", label: "Altura", obrigatorio: true, linha: 1 },
    { id: "largura", tipo: "medida", unidade: "m", label: "Largura", obrigatorio: true, linha: 1 },
    {
      id: "caixa",
      tipo: "medida",
      unidade: "cm",
      casasDecimais: 1,
      casasInteiras: 2,
      label: "Caixa",
      obrigatorio: true,
      linha: 1,
    },
    { id: "padraoMadeira", tipo: "texto", label: "Padrão de madeira", obrigatorio: true, linha: 1 },
    {
      id: "medidasGuarnicao",
      tipo: "medida",
      unidade: "cm",
      casasDecimais: 1,
      casasInteiras: 2,
      label: "Medidas de guarnição",
      obrigatorio: true,
      linha: 2,
    },
    {
      id: "ladosGuarnicao",
      tipo: "opcao-unica",
      label: "Lados",
      opcoes: ["UM LADO", "DOIS LADOS"],
      exibirApenasSelecionadas: true,
      linha: 2,
    },
    {
      id: "tipoPalheta",
      tipo: "opcao-unica",
      label: "Tipo de palheta",
      opcoes: ["FRANCESA", "SEMI-PORTUGUESA", "RETA"],
      obrigatorio: true,
      exibirApenasSelecionadas: true,
    },
    {
      id: "formatoEsquadria",
      tipo: "opcao-unica",
      label: "Formato da esquadria",
      opcoes: ["RETO", "ARCO"],
      exibirApenasSelecionadas: true,
    },
    {
      id: "comSemFerragem",
      tipo: "opcao-unica",
      label: "Ferragem",
      opcoes: ["COM FERRAGENS", "SEM FERRAGENS"],
      obrigatorio: true,
      exibirApenasSelecionadas: true,
      linha: 3,
    },
    {
      id: "acabamentoFerragem",
      tipo: "opcao-unica",
      label: "Acabamento da ferragem",
      opcoes: ["CROMADO", "LO", "PRETO"],
      dependeDe: { campoId: "comSemFerragem", valores: ["COM FERRAGENS"] },
      exibirApenasSelecionadas: true,
      linha: 3,
    },
    {
      id: "tipoAbertura",
      tipo: "opcao-unica",
      label: "Tipo de abertura",
      opcoes: [
        "CORRER",
        "ABRIR/ABRIR",
        "CORRER/ABRIR",
        "PANTOGRÁFICA",
        "CAMARÃO",
        "GIRO",
        "PIVOTANTE",
        "BASCULANTE",
        "MAX-AR",
        "GUILHOTINA/ABRIR",
        "BY WINDOW",
      ],
      obrigatorio: true,
      exibirApenasSelecionadas: true,
      linha: 4,
    },
    {
      id: "ladoAbertura",
      tipo: "opcao-unica",
      label: "Lado de abertura",
      opcoes: ["ESQUERDA", "DIREITA", "CENTRAL", "BANDA LOUCA"],
      obrigatorio: true,
      exibirApenasSelecionadas: true,
      linha: 4,
    },
    {
      id: "vidros",
      tipo: "opcao-unica",
      label: "Vidros",
      opcoes: [
        "CONSIDERAR QUANTIDADE DE VIDROS DO DESENHO",
        "FAZER QUANTIDADE E TAMANHOS PROPORCIONAIS ÀS MEDIDAS DA PEÇA",
        "QUANTIDADES E TAMANHOS A CRITÉRIO DA FÁBRICA",
      ],
      dependeDe: { campoId: "categoria", valores: ["PANORÂMICO", "SEMI-PANORÂMICO", "QUADRICULADO"] },
      exibirApenasSelecionadas: true,
    },
  ],
};
