import type { ConfigProduto } from "./tipos";

export const portaEspecial: ConfigProduto = {
  id: "porta-especial",
  nome: "Porta Encomenda Especial",
  tituloDocumento: "ENCOMENDA ESPECIAL PORTAS",
  prazoEntregaDias: 60,
  campoLargura: "larguraFolha",
  campoAltura: "alturaFolha",
  campos: [
    { id: "tipoFolha", tipo: "opcao-unica", label: "Tipo", opcoes: ["SÓ FOLHA", "CONJUNTO"], obrigatorio: true },
    { id: "alturaFolha", tipo: "medida", unidade: "m", label: "Altura da folha", obrigatorio: true },
    { id: "larguraFolha", tipo: "medida", unidade: "m", label: "Largura da folha", obrigatorio: true },
    {
      id: "caixaBatente",
      tipo: "medida",
      unidade: "cm",
      casasDecimais: 1,
      casasInteiras: 2,
      label: "Caixa do batente",
      dependeDe: { campoId: "tipoFolha", valores: ["CONJUNTO"] },
    },
    { id: "padraoMadeira", tipo: "texto", label: "Padrão de madeira", obrigatorio: true },
    {
      id: "espessuraFolha",
      tipo: "medida",
      unidade: "cm",
      casasDecimais: 1,
      label: "Espessura da folha",
      obrigatorio: true,
    },
    {
      id: "medidasGuarnicao",
      tipo: "medida",
      unidade: "cm",
      casasDecimais: 1,
      casasInteiras: 2,
      label: "Medidas de guarnição",
      dependeDe: { campoId: "tipoFolha", valores: ["CONJUNTO"] },
    },
    {
      id: "ladosGuarnicao",
      tipo: "opcao-unica",
      label: "Lados",
      opcoes: ["UM LADO", "DOIS LADOS"],
      dependeDe: { campoId: "tipoFolha", valores: ["CONJUNTO"] },
    },
    {
      id: "tipoAbertura",
      tipo: "opcao-unica",
      label: "Tipo de abertura",
      opcoes: ["GIRO", "PIVOTANTE", "CAMARÃO"],
      dependeDe: { campoId: "tipoFolha", valores: ["CONJUNTO"] },
    },
    {
      id: "ladoAbertura",
      tipo: "opcao-unica",
      label: "Lado de abertura",
      opcoes: ["ESQUERDO", "DIREITO", "CENTRAL"],
      dependeDe: { campoId: "tipoFolha", valores: ["CONJUNTO"] },
    },
  ],
};
