import type { ConfigProduto } from "./tipos";

export const portaMarcenaria: ConfigProduto = {
  id: "porta-marcenaria",
  nome: "Porta Marcenaria Madel",
  tituloDocumento: "ENCOMENDA ESPECIAL PORTAS",
  permiteGerarImagem: true,
  prazoEntregaDias: 60,
  campoLargura: "larguraFolha",
  campoAltura: "alturaFolha",
  campos: [
    { id: "alturaFolha", tipo: "medida", unidade: "m", label: "Altura da folha", obrigatorio: true, linha: 2 },
    { id: "larguraFolha", tipo: "medida", unidade: "m", label: "Largura da folha", obrigatorio: true, linha: 2 },
    {
      id: "espessuraFolha",
      tipo: "opcao-unica",
      label: "Espessura da folha",
      opcoes: ["35MM", "45MM"],
      obrigatorio: true,
      linha: 2,
    },
    {
      id: "madeira",
      tipo: "opcao-unica",
      label: "Padrão de madeira",
      opcoes: ["IMBUIA", "CEDRO", "TAUARI"],
      obrigatorio: true,
    },
    { id: "tipoFolha", tipo: "multipla-escolha", label: "Tipo", opcoes: ["FRISADA", "RASGADA"] },
    {
      id: "friso",
      tipo: "opcao-unica",
      label: "Friso",
      opcoes: ["1 LADO", "2 LADOS"],
      dependeDe: { campoId: "tipoFolha", valores: ["FRISADA"] },
    },
    { id: "modeloFriso", tipo: "texto", label: "Modelo de friso", linha: 1 },
    {
      id: "profundidadeFriso",
      tipo: "medida",
      unidade: "cm",
      casasDecimais: 2,
      label: "Profundidade do friso",
      linha: 1,
    },
    { id: "cava", tipo: "opcao-unica", label: "Cava", opcoes: ["FOLEADA", "SEM FOLEAR"] },
    {
      id: "cavaLados",
      tipo: "opcao-unica",
      label: "Cava",
      opcoes: ["1 LADO", "2 LADOS"],
      dependeDe: { campoId: "cava", valores: ["FOLEADA", "SEM FOLEAR"] },
      ocultarLabelDocumento: true,
    },
    { id: "ladoMacaneta", tipo: "texto", label: "Lado da maçaneta" },
  ],
};
